Default to an empty dict instead of None
This avoids the following failure:

```
⋊> passpie nocommand
Traceback (most recent call last):
...
TypeError: argument of type 'NoneType' is not iterable
```